server:
  port: 8082

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: 'http://localhost:8090'
          predicates:
            - Path=/v1/students/**
        - id: courses
          uri: 'http://localhost:9090'
          predicates:
            - Path=/v1/courses/**
eureka:
  client:
    register-with-eureka: false